# -*- coding: utf-8 -*-
"""c116.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10dd32wYmnVunFHqDP_9gpW5uhaszGQwa
"""

from google.colab import files
data_to_load = files.upload()

import pandas as pd
import plotly.express as px
df = pd.read_csv("logistics_data.csv")
salary = df["EstimatedSalary"].tolist()
purchase = df["Purchased"].tolist()
print(len(salary))
fig = px.scatter(x = salary, y = purchase)
fig.show()

import plotly.graph_objects as go
salary = df["EstimatedSalary"].tolist()
age = df["Age"].tolist()
purchase = df["Purchased"].tolist()
colors = []
for data in purchase:
  if data == 1:
    colors.append("green")
  else:
    colors.append("red")  
fig = go.Figure(data = go.Scatter(x = salary, y = age, mode = 'markers', marker = dict(color = colors)))    
fig.show()

"""You can see that the plot is split into 2 parts, the red dots show the people who haven't bought the phone while the green dots show the people who are willing to buy the phone. By using the machine learning libraries we will build a model to predict if the person will buy a phone or not, to do that we will divide the data into 2 parts. We will use the first part, to train this model on it and using the other part of the data to test the model. This is a general practice used by data scientists."""